# Generated by Django 4.2 on 2023-07-07 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aceptada', models.BooleanField(default=False)),
                ('despachada', models.BooleanField(default=False)),
                ('productos', models.ManyToManyField(through='api.DetalleOrdenPedido', to='api.producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleordenpedido',
            name='orden_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordenpedido'),
        ),
        migrations.AddField(
            model_name='detalleordenpedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
        ),
    ]
