# Generated by Django 4.2 on 2023-07-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ordenpedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordenpedido',
            name='productos',
            field=models.ManyToManyField(related_name='detalles_orden_pedido', to='api.producto'),
        ),
    ]
